### ISSUE TITLE
统计服务器挂了？

### ISSUE THREAD

**Issue by f841705799** [ElainaMoe/MHYY-AutoCheckin#10]
<img width="630" alt="image" src="https://user-images.githubusercontent.com/11625013/184189340-28f9f38a-7db7-46b6-bb3f-e401eef1a700.png">

**Comment by GamerNoTitle** [comment]
好像是的，先把统计给关了吧

**Comment by GamerNoTitle** [comment]
刚刚改了一下 对统计部分进行错误捕获
这样统计服务器崩了也不影响脚本使用了

**Comment by GamerNoTitle** [comment]
更新一下就行
