### ISSUE TITLE
关于KeepAlive的action

### ISSUE THREAD

**Issue by lycorisor** [ElainaMoe/MHYY-AutoCheckin#11]
刚刚看了一下这个action的配置文件，发现它取了一个预期之外的值（教程中没有提到怎么设置），secret中的GITHUB_TOKEN，提交实际上是依赖于用户的令牌验证，如果这一步没有设置的话会造成提交失败，希望教程能改进一下

**Comment by GamerNoTitle** [comment]
好的 晚些时候加上

**Comment by GamerNoTitle** [comment]
已加 https://bili33.top/posts/MHYY-AutoCheckin-Manual/#%E8%87%AA%E5%8A%A8%E4%BF%9D%E6%B4%BB

**Comment by lycorisor** [comment]
呃还要在项目secrets里面设置GITHUB_TOKEN的值为获取到的那个token吧

**Comment by GamerNoTitle** [comment]
事实上你应该是加不进去的，因为会这么提示
![Screenshot_2022-08-23-07-16-33-242_com microsoft emmx](https://user-images.githubusercontent.com/28426291/186035637-1d4033a6-49d9-4aa1-9d04-6f83a756eba3.jpg)
![Screenshot_2022-08-23-07-16-13-054_com microsoft emmx](https://user-images.githubusercontent.com/28426291/186035708-5c38355b-d638-4d59-a8c6-e57db357550b.jpg)

---
在Developer settings里面添加GITHUB_TOKEN也只是因为以前的Action需要，现版本应该是不需要的，这个变量会在Actuon运行的时候自动获取，换言之，用户在自动续期上面其实什么也不用做

**Comment by lycorisor** [comment]
刚刚看了一下，确实是的
https://docs.github.com/cn/actions/security-guides/automatic-token-authentication
那就，不加了吧(doge
