### ISSUE TITLE
【青龙面板】将配置写入config.json，使用Action版本，提示json解析错误

### ISSUE THREAD

**Issue by just6a6name** [ElainaMoe/MHYY-AutoCheckin#12]
json配置文件照着填的
就是一直报错，大佬帮忙康康
还有青龙的Python版本有点高😂

main报错
## 开始执行... 2022-08-23 15:28:33

Traceback (most recent call last):
  File "/ql/data/scripts/ElainaMoe_MHYY-AutoCheckin/main.py", line 24, in <module>
    config = json.loads(os.environ.get('config'))
  File "/usr/lib/python3.9/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit

## 执行结束... 2022-08-23 15:28:34 耗时 1 秒

index没问题
## 开始执行... 2022-08-23 15:28:30

从官方API获取到云·原神最新版本号：2.6.0

## 执行结束... 2022-08-23 15:28:30 耗时 0 秒

**Comment by lycorisor** [comment]
呃config不是直接写到config.json文件里面的，是要添加到action的secrets里面的
![Uploading 屏幕截图 2022-08-23 190507.png…]()

**Comment by just6a6name** [comment]
> 呃config不是直接写到config.json文件里面的，是要添加到action的secrets里面的 ![屏幕截图 2022-08-23 190507](https://user-images.githubusercontent.com/110145061/186142801-0f859928-a4c9-41fe-b195-41b937954e81.png)

其实不是用github action跑的，是青龙😂

**Comment by GamerNoTitle** [comment]
![IMG_20220824_072251](https://user-images.githubusercontent.com/28426291/186282956-931427da-4342-4514-b42b-a87af73fd27f.jpg)
在圈圈的地方把#号删掉，在标#的地方那行前面加个#

**Comment by just6a6name** [comment]
> ![IMG_20220824_072251](https://user-images.githubusercontent.com/28426291/186282956-931427da-4342-4514-b42b-a87af73fd27f.jpg) 在圈圈的地方把#号删掉，在标#的地方那行前面加个#

OK，没问题了，谢谢大佬
顺便问一下怎么调push+推送日志😂

**Comment by GamerNoTitle** [comment]
push+是个啥……消息推动服务嘛
如果你想推送完整的日志 推荐加一个Logger重定向输出到文件 然后直接推送文件里面的内容
如果是想完成后推送一个提示的话直接在后面进行一个HTTP请求就好了

**Comment by just6a6name** [comment]
> push+是个啥……消息推动服务嘛 如果你想推送完整的日志 推荐加一个Logger重定向输出到文件 然后直接推送文件里面的内容 如果是想完成后推送一个提示的话直接在后面进行一个HTTP请求就好了

好的谢谢大佬，大佬辛苦了😘

**Comment by GamerNoTitle** [comment]
例如，GET请求
```python
r.get(url)
```
POST请求
```python
r.post(url)
```

**Comment by GamerNoTitle** [comment]
根据自己需要去写就行了 这里的`r`是前面`import requests as r`里面的`r`
url是pushplus的提供的链接 用的时候注意看文档

**Comment by just6a6name** [comment]
> 根据自己需要去写就行了 这里的`r`是前面`import requests as r`里面的`r` url是pushplus的提供的链接 用的时候注意看文档

收到😉
