### ISSUE TITLE
Action里为什么会“This job was skipped”

### ISSUE THREAD

**Issue by redkamih** [ElainaMoe/MHYY-AutoCheckin#13]
让它自动运行就会这样，手动运行一切正常

**Comment by GamerNoTitle** [comment]
目前我能够看到的解释是说Github Action的资源调度问题，根据官方的说法为`It might be possible that your job caused the github hosted runner to run out of diskspace, then the runner died.`，而脚本必然是不会导致存储空间占用满的（那是当然的嘛，就那么几十kb），所以只可能是在同一台机器上运行的Action把空间占满了（Action机器是全网共用的），我目前能够看到的原因是这个

**Comment by GamerNoTitle** [comment]
（话说以前没有这个问题的来着……）

**Comment by GamerNoTitle** [comment]
待我去社区问一下先 :P

**Comment by Mabbs** [comment]
> （话说以前没有这个问题的来着……）

我猜github前几天修改了action的变量，把`github.event.repository.owner.id == github.event.sender.id`删掉就好了（具体可以看我的fork版本）

**Comment by GamerNoTitle** [comment]
> #14

Thanks.

**Comment by valetzx** [comment]
请问github action这些变量可以在哪找，这个应该是20天前改的。

**Comment by Ayx03** [comment]
> 请问github action这些变量可以在哪找，这个应该是20天前改的。
参照文档：https://bili33.top/posts/MHYY-AutoCheckin-Manual/

**Comment by valetzx** [comment]
指的是 `github.event.repository.owner.id == github.event.sender.id` 这样的变量文档 @Mabbs
