### ISSUE TITLE
Github Action卡在Run Script

### ISSUE THREAD

**Issue by KremeCN** [ElainaMoe/MHYY-AutoCheckin#16]
![Screenshot_2022-11-25-23-32-57-11](https://user-images.githubusercontent.com/63275597/204017077-0eaebabc-e299-442c-9a7d-f63201a77b05.png)
如何解决，我是小白，求助大佬

logs:
https://github.com/KremeCN/MHYY-AutoCheckin/commit/f845de175c882de925236198ad0f34955fdbe24b/checks/9710224403/logs

**Comment by KremeCN** [comment]
刚看了别的帖子，是随机睡眠啊，知道了。

**Comment by KremeCN** [comment]
刚看了别的issue，是随机睡眠啊，知道了

**Comment by GamerNoTitle** [comment]
= =
